### ISSUE TITLE
Support for USB button?

### ISSUE THREAD

**Issue by jupiispa** [katie-snow/Ultimarc-linux#18]
Hi. 

Would it be possible to support USB Button? 
   **Bus 001 Device 006: ID d209:1200 Ultimarc**

Looking at the official SDK, there are 3 parameters you can set in the USB button: 
PACDRIVE_API BOOL __stdcall USBButtonConfigurePermanent(INT id, PBYTE data);
PACDRIVE_API BOOL __stdcall USBButtonConfigureTemporary(INT id, PBYTE data);
PACDRIVE_API BOOL __stdcall USBButtonConfigureColor(INT id, BYTE red, BYTE green, BYTE blue);

And one parameter that can be read:
PACDRIVE_API BOOL __stdcall USBButtonGetState(INT id, PBOOL state);

**Comment by katie-snow** [comment]
At this time I don't have plans to implement the functionality for this product.  I will leave the issue open for reference if I do start supporting USB Button.

**Comment by OzFalcon** [comment]
Jupiispa,
Are we talking about http://www.usbbutton.com/
I am guessing you would not be using this in an arcade environment.
(Where IPac/Pacdrive would be more appropriate for multi switch setup).
What would you be using this for?

**Comment by katie-snow** [comment]
This hardware is now supported by pull request #38
