### ISSUE TITLE
Checksum/Control byte incorrectly identified

### ISSUE THREAD

**Issue by OzFalcon** [katie-snow/Ultimarc-linux#26]
Previously I noticed you had written byte 0x30, While Andy's data dump showed 29.
This byte is in fact the calculated checksum value, So it's going to change depending on the key data.

As far as I can gather, 2014 & 2015 cards do not require this checksum value.
I'm not sure if the value is simply ignored or if it now serves some other purpose....?
Perhaps it's worth zeroing it to be safe?

**Comment by OzFalcon** [comment]
![byte_0x30](https://cloud.githubusercontent.com/assets/13824723/12533494/e9d2a6fa-c284-11e5-92b3-f0a0ba70ec8c.png)
![byte_0x29](https://cloud.githubusercontent.com/assets/13824723/12533496/eec5a540-c284-11e5-8085-a3c03347646a.png)

**Comment by OzFalcon** [comment]
Note, It's the byte after that checksum value that appears to be the control byte for 2011 ipac cards.
ie. Write to ram, Reset factory defaults etc.

**Comment by katie-snow** [comment]
#28 merged.
