### ISSUE TITLE
Support for I-PAC VE

### ISSUE THREAD

**Issue by A-Coward** [katie-snow/Ultimarc-linux#3]
Hi.  Just wondering if you have tried adding support for the I-PAC VE (Value Edition).

This edition of the I-PAC, which is equivalent to the older I-PAC 2, but without EEPROM
to persist codesets across power loss, has a different USB VID/PID than the other products,
so does not get properly detected:

Bus 004 Device 003: ID d209:0301 Ultimarc I-PAC Arcade Control Interface

Anyway, I tried modifying ipac.h to match on the above VID/PID to see if things
would work, but I get the following error when running umtool:

[INFO] (ultimarc.c:45) Loading ipac2.json...
[INFO] (ultimarc.c:100) Updating IPAC2/MinIPAC board...
[ERROR] (common.c:59: errno: Invalid argument) Unable to claim interface.
[INFO] (ultimarc.c:159) Update failed!

Any suggestions?

Thanks.

**Comment by katie-snow** [comment]
You will need to change the 21-ultimarc.rules file with the additional vendor and products ids.  Then copy it to the rules directory again.  This should be why you aren't able to claim the interface.

**Comment by A-Coward** [comment]
Hi, Katie.  Thanks for the quick response.

I actually did modify the 21-ultimarc.rules file (sorry, I failed to mention that).  The error I got was actually with the change done.  In fact, before I made that change I got a different error (common.c:59).

**Comment by katie-snow** [comment]
Try changing the autoconnect.  In IPAC.c line 160 where the openUSB function is called, change the last parameter to 0.  If this doesn't help then I will need to see the output from the call dmesg after you connect the I-PAC VE to see if there is a different interface we should be trying to connect to.

**Comment by A-Coward** [comment]
Hi, Katie.

I still get the exact same error after modifying the call to openUSB().

The dmesg output is as follows:

[50648.522898] usb 1-1.2: new full-speed USB device number 18 using dwc_otg
[50648.634957] usb 1-1.2: New USB device found, idVendor=d209, idProduct=0301
[50648.634982] usb 1-1.2: New USB device strings: Mfr=1, Product=1, SerialNumber=0
[50648.635000] usb 1-1.2: Product: Ultimarc I-PAC
[50648.635017] usb 1-1.2: Manufacturer: Ultimarc I-PAC
[50648.647183] input: Ultimarc I-PAC Ultimarc I-PAC as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.0/0003:D209:0301.0018/input/input23
[50648.648297] hid-generic 0003:D209:0301.0018: input,hidraw0: USB HID v1.11 Keyboard [Ultimarc I-PAC Ultimarc I-PAC] on usb-bcm2708_usb-1.2/input0



Thanks...

**Comment by katie-snow** [comment]
Change the interface from 2 to 0 and see what that gives you.  You may want to change the autoconnect back to 1 the first time you try interface 0.

**Comment by A-Coward** [comment]
Hi, Katie.

The tools now reports that the programming was successful after changing the interface to 0.  However, it does not look as if anything gets changed on the I-PAC as it will still output the default keystrokes instead of the new keystrokes defined in the json file.  Anyway, I did some searching and found a utility called "ipacutil" which mentions that the programming sequence for some VE models are different to that of the I-PAC 2.

**Comment by katie-snow** [comment]
I am glad the interface changed worked.  Bummer that it didn't configure the board.  I will look at the ipacutil code and see if the header bits need to be different for the VE.  If I can't figure it out through his code then I would have to look at some USB Wireshark output from Windows to figure out what I need to send to the card.  I will get back with you after I look the code over.

**Comment by katie-snow** [comment]
Looking at the ipacutil code.  The older boards use different USB messages than the current IPAC's.  It looks to be the same messages that program the Ultistik board, which I have the code for.  It could be possible to merge the two code groups together and see if that will program to board.

**Comment by OzFalcon** [comment]
It would be great if you could add support for the older I-PAC boards.
The main difference is the older board (D209:0301) require handshake.

NOTE:
The D209:0301 board is an IPAC ONE
The D208:0310 board is an IPAC2 2014
The D209:0420 board is an IPAC2 2015

IPAC Device List
----------------
YEAR	ID			Model	Program
2011:	D209:0301	VE		IPacUtil V0.7
2012:	D209:0310	??		???
2013:	D208:0310	VE		UMTool 
2015: 	D209:0420	Full		UMTool

Unfortunately I don't have any D209:0301 boards to test, But A-Coward can test that board if he has one. I have both D208:0310 & D209:0420 boards here though.

**Comment by OzFalcon** [comment]
I have come to the conclusion that supporting the older ipac devices is not a good use of time/programming. Read on to see why.

It would appear that pre 2013 ipac cards required a checksum to be calculated and included in the data sent.

ipac_prog.h
/* Programming order is: shift code, unshifted codes, shifted codes, checksum, control, macros, zero pad to 96 */

The main reason is there are so many variants of said cards.
When Travis's IpacUtil already caters for most of them, It seems a waste to reinvent the wheel.
It may also be noted that these cards are a diminishing quantity - So the usefulness of including them in UMTool would be limited and better off redirecting to IpacUtil IMHO. 

ipac_prog.h
/*************************************************************
 * New I-PAC2 (FS32) - 32 inputs, 28 shifted codes           *
 * I-PAC4 - 56 inputs, 56 shifted codes                      *
 * J-PAC - 28 inputs, 28 shifted codes                       *
 * ??? is there a J-PAC 32 input ???                         *
 * I-PACVE - 32 inputs, 28 shifted codes, RAM only, no flash *
 * MINIPac - 32 inputs, 28 shifted - same as I-PAC2          *
 * I believe the MINIPac also came in a 28-input version     *
 *************************************************************/

**Comment by OzFalcon** [comment]
Perhaps it should be noted in the UMTool readme that pre 2013 cards should be programmed with Travis's IpacUtil or WinIpac V1.

**Comment by katie-snow** [comment]
I agree with not implementing the support for the older boards.  I will put in a note for using IpacUtil or WinIpac V1 for the older boards.

**Comment by OzFalcon** [comment]
This issue should probably be closed now.
