### ISSUE TITLE
2009 IPAC2 vendor:d209  product:0301  will not program

### ISSUE THREAD

**Issue by raunraun** [katie-snow/Ultimarc-linux#33]
I have an IPAC-2 purchased in 2009, that identifies itself 
    `Bus 003 Device 007: ID d209:0301 Ultimarc I-PAC Arcade Control Interface`

Looking at defines ipac.h vendor d209 would map to a 2015 board, which my board is not.

My board has ps/2 ports on the board, but shipped with a ps/2 to USB cable.  I think I remember programming this board with the old winipac software may years ago, so it should be possible to program this board. 

I've hacked in the vendor and product ids for this board, but libusb_claim_interface always seems to fail.

Is this board programmable through libusb?  Are there data sheets available for this board?  I'll keep tinkering unless someone says i'm wasting my time.

**Comment by raunraun** [comment]
lsusb -D /dev/bus/usb/003/007 
    Device: ID d209:0301 Ultimarc I-PAC Arcade Control Interface
    Couldn't open device, some information will be missing
    Device Descriptor:
      bLength                18
      bDescriptorType         1
      bcdUSB               2.00
      bDeviceClass            0 (Defined at Interface level)
      bDeviceSubClass         0 
      bDeviceProtocol         0 
      bMaxPacketSize0         8
      idVendor           0xd209 Ultimarc
      idProduct          0x0301 I-PAC Arcade Control Interface
      bcdDevice            0.23
      iManufacturer           1 
      iProduct                1 
      iSerial                 0 
      bNumConfigurations      1
      Configuration Descriptor:
        bLength                 9
        bDescriptorType         2
        wTotalLength           34
        bNumInterfaces          1
        bConfigurationValue     1
        iConfiguration          1 
        bmAttributes         0x80
          (Bus Powered)
        MaxPower              100mA
        Interface Descriptor:
          bLength                 9
          bDescriptorType         4
          bInterfaceNumber        0
          bAlternateSetting       0
          bNumEndpoints           1
          bInterfaceClass         3 Human Interface Device
          bInterfaceSubClass      1 Boot Interface Subclass
          bInterfaceProtocol      1 Keyboard
          iInterface              1 
            HID Device Descriptor:
              bLength                 9
              bDescriptorType        33
              bcdHID               1.11
              bCountryCode           33 US
              bNumDescriptors         1
              bDescriptorType        34 Report
              wDescriptorLength      63
             Report Descriptors: 
               ** UNAVAILABLE **
          Endpoint Descriptor:
            bLength                 7
            bDescriptorType         5
            bEndpointAddress     0x81  EP 1 IN
            bmAttributes            3
              Transfer Type            Interrupt
              Synch Type               None
              Usage Type               Data
            wMaxPacketSize     0x0010  1x 16 bytes
            bInterval               5

**Comment by OzFalcon** [comment]
The 209:301 cards are supported by Travis's utility, Not umtoo.
https://github.com/katie-snow/Ultimarc-linux/issues/3
It would be great if you could add support for the older I-PAC boards.
The main difference is the older board (D209:0301) require handshake.

NOTE:
The D209:0301 board is an IPAC ONE
The D208:0310 board is an IPAC2 2014
The D209:0420 board is an IPAC2 2015
IPAC Device List

YEAR ID Model Program
2011: D209:0301 VE IPacUtil V0.7
2012: D209:0310 ?? ???
2013: D208:0310 VE UMTool
2015: D209:0420 Full UMTool

You can download Travis's utility here:
http://www.zumbrovalley.net/readpost.php?artid=6

Or you can download an updated version (Yet to be checked/posted by Travis) here:
http://zsystem.bden.org/ipacutil_0_20.tar.gz
