### ISSUE TITLE
Ultistik 360 analog mode seems not supported/not working

### ISSUE THREAD

**Issue by maziac** [katie-snow/Ultimarc-linux#36]
Hi,

if I use "-" in a map for the UltraStik 360 I get an error 
"Error at index nn in 'map' array, entry is '.'

Looking at the source code the "-" is mapped to 0x00 which might be wrong.

Or is there any other way to enter analog map.

BR

**Comment by katie-snow** [comment]
Could you include your configuration file to this thread?

**Comment by maziac** [comment]
Hi,

do you mean the 'configure' file?

It is not a build problem, but a runtime error I get.

Meanwhile I changed the code so that it simply does not the error and it's working.
I.e. it still prints the error but nevertheless it's working.


br,
Thomas


--- a/Ultimarc/src/libs/ultistik.c
+++ b/Ultimarc/src/libs/ultistik.c
@@ -72,7 +72,7 @@ bool validateUltistikData(json_object* jobj)
             if (strcmp(&invalidKey, &data) == 0)
             {
               log_err ("Error at index %i in 'map' array, entry is '%s'", idx, 
-              valid = false;
+//              valid = false;
             }
           }
         }

**Comment by katie-snow** [comment]
I wanted the json configuration file you where using, but I no longer need it.  I was able to reproduce the problem.  I should have a solution out there for you in a couple of hours.

**Comment by katie-snow** [comment]
I have placed the fix in branch ultistik_analog.  I have tested, but if you would test and let me know if it works for you.

Thanks

**Comment by maziac** [comment]
I could verify the fix. It's working like a charm.
Thank you very much.
