### ISSUE TITLE
U-HID Configuration format?

### ISSUE THREAD

**Issue by katie-snow** [katie-snow/Ultimarc-linux#42]
I am starting work on the U-HID boards and I am trying to work out the configuration format.  I see two format options.  If you want to see what the GUI looks like it is at http://www.u-hid.com/home/u_config_utils.php.

Each pin can be one of 7 different options.  disabled, switch, quadrature, analog axis, LED, +5v or ground.  The first format option would be to have each of these options as a group and place pins under them with the corresponding data.  I would not have disabled in this format.  The assumption would be if the pin is not present in any of the other options then it is disabled.
[Option 1.txt](https://github.com/katie-snow/Ultimarc-linux/files/601877/Option.1.txt)

The second format option is to have the pin and then one of the options with the corresponding data.
[Option 2.txt](https://github.com/katie-snow/Ultimarc-linux/files/601879/Option.2.txt)

Anyone have pro/cons for either option?

Here are what I have come up with.  Option 1 is visually nice to see what group of pins is doing.  Option 2 is in line with all the other board configurations and does order of operation or selection.  Pick a pin then decide what that pin would do.

**Comment by OzFalcon** [comment]
I am not sure if there are any limitations to the number of analog/gamepad assignments under Linux.
Groups might coincide with the "Modular 8-way + ground harnesses available."
Option 2 divided into Modular 8 way groups is one possibility.

Control counts which can be configured:
Total 50 connection pins.
Max 8 analog axes on 50 possible pins (Windows limitation)
Max 32 Gamepad buttons on 50 possible pins (Windows limitation)
Max 8 Quadrature mouse devices on 16 possible pins out of the 50.
Max 3 Quadrature mouse axes (X, Y and Z, Windows limitation)
Max 50 keyboard keys on 50 possible pins.
Max 16 LEDs in any combination of PC or U-HID controlled. (USB 500 mA current limitation).
Max 50 low-current output drivers.

**Comment by OzFalcon** [comment]
http://www.u-hid.com/home/cms.php?page_id=8
Note that only certain pins can be configured for quadrature devices. These can be seen in U-Config by clicking on the "Quadrature" line in the PCB image. Appropriate pins will be highlighted. Two pins are used per device. An X-Y device such as a trackball counts as two devices and therefore uses 4 pins.
