### ISSUE TITLE
Release 1.1 archive missing "21-ultimarc.rules"

### ISSUE THREAD

**Issue by OzFalcon** [katie-snow/Ultimarc-linux#46]
The release package in the downloads section is missing the "21-ultimarc.rules" file.
https://github.com/katie-snow/Ultimarc-linux/releases/download/1.1.0/ultimarc-linux-1.1.tar.gz

**Comment by katie-snow** [comment]
Adding autogen.sh in addition to 21-ultimarc.rules file

**Comment by katie-snow** [comment]
Added new archive file to the release named ultimarc-linux-1.1.update.tar.gz.
