### ISSUE TITLE
USBButtonConfigureColor function.

### ISSUE THREAD

**Issue by spdimaio** [katie-snow/Ultimarc-linux#49]
Hello,
I’m playing with the USBButton in a Linux project and would like to use the following API function that is available in the Windows lib from Ultimarc. Is this function available in the linux version of the library? If not, how difficult would it be to add?

bool USBButtonConfigureColor(char red, char green, char blue)

Thanks in advance,
Simon

**Comment by katie-snow** [comment]
Hi Simon,

Looking at the function information in the SDK I have most likely not implemented that behavior.  I have implemented the USBButtonConfigurePermanent function.  

Adding the functionality for the USBButtonConfigureColor would not be hard once I have the USB data format.  The functionality would be in JSON configuration file format like all the other configurations.

**Comment by spdimaio** [comment]
Hi Katie,

Here is feedback from Andy Warne on the USB data format:

The data required to be sent is very simple though. Its just a 4 byte
packet:

01

Red value

Green value

Blue value


Would it be possible to add the following function to the library?

PACDRIVE_API BOOL __stdcall USBButtonConfigureColor(INT id, BYTE red, BYTE
green, BYTE blue);


Thanks in advance,

Simon

**Comment by katie-snow** [comment]
I will be happy to add this to the library.  Give me a couple of weeks, but I will get it in.

**Comment by spdimaio** [comment]
Thanks Katie,
Simon

**Comment by katie-snow** [comment]
This enhancement is in branch usbbutton.  It to master when I create the next release.

**Comment by spdimaio** [comment]
Thanks very much Katie -- much appreciated. Were you able to test on a physical USBbutton device?

Simon

**Comment by katie-snow** [comment]
Yes I did testing on the physical device.  It maintained the color until unplugged, then returned to stored color when plugged in.

**Comment by spdimaio** [comment]
Excellent, thanks very much Katie. 

Regards,
Simon
