### ISSUE TITLE
Install for dummies

### ISSUE THREAD

**Issue by KrunchMuffin** [katie-snow/Ultimarc-linux#59]
Is there an install for dummies of linux I can follow? I know my way around a bit, but not sure how to even start this. This is my last resort in getting my u360 working without erratic behaviour b4 i throw in the towel with this damn rpi.

**Comment by katie-snow** [comment]
The Readme.md file on the main page tells you what you need to install on your machine.  Also this [link](https://retropie.org.uk/forum/topic/1998/configuring-i-pac-2-with-rpi3/13) gives some more instructions.
