### ISSUE TITLE
Option to write to RAM or FLASH for 2011 IPac cards.

### ISSUE THREAD

**Issue by OzFalcon** [katie-snow/Ultimarc-linux#6]
This is a must have option to save our IPACS from flash destruction.
It's not uncommon to program the IPAC at the start of each boot - Regardless of model.
And when multiple emulators are used, The IPAC may be re-programed many times a day.

This is causing unnecessary wear to the flash storage and may even lead to the device failure.
A write to ram option is required to solve this issue and avoid flash storage failure.

**Comment by katie-snow** [comment]
Are you wanting this for older IPAC boards?

**Comment by katie-snow** [comment]
Could you please contact Andy about this.  He is interested in figuring out what you need.  Thanks

**Comment by OzFalcon** [comment]
After checking out the newer 2015 ipac2 and WinIPAC V2 software, It appears the newer 2015 ipac devices do not have the write to ram option.
(Or the WinIPAC V2 utility doesn't currently support write to ram for the 2015 devices)

While all my Pre 2015 devices are VE versions (No flashram), The option to write to ram for pre 2015 devices would be very useful for other users that own flashable pre 2015 ipacs.

Regarding newer 2015 ipacs, I will have to ask Andy if the VE (No Flashram) version is available.

**Comment by OzFalcon** [comment]
Just checking out the code in ipacutil by travis.

Here we see the ram only option is controlled by the C shift operator.
Note this is the older IPAC card 2011: D209:0301.

#define CONTROL_RAM_ONLY         (1 << 2)

ie. ..00000100
This is possibly the same for the 2014 ipac2 model.
Obviously this is not applicable to the 2015 model.

We just need to change that byte on the control character sent to the ipac2.

**Comment by OzFalcon** [comment]
Small test code to change byte seems to work ok and just needs to be made a command line option.
Note I refer to it as Control data where you referred to it as Macro data.

void updatePre2015IPAC2Board (json_object *jobj, unsigned char* barray)
{
  json_object *shiftKey = NULL;
  json_object *pins = NULL;

  /* Header data */
  unsigned char header[4] = {0x50, 0xdd, 0x00, 0x00};
  memcpy (barray, &header, sizeof(header));

  /* Control data */
  barray[65] = 0x29;
  if (true) {
  barray[65] |= (1 << 2);
  }

  json_object_object_get_ex(jobj, "1/2 shift key", &shiftKey);
  barray[4] = convertIPAC(shiftKey);

  json_object_object_get_ex(jobj, "pins", &pins);
  populateBoardArray(PRE_IPAC2_BOARD, pins, &barray[4]);
}

**Comment by katie-snow** [comment]
I have make a fix with pull request 14.  I have added an optional entry into the 2014 ipac2 json file "write to ram".  If it is true then the control data is set to 0x2d, write to ram.  If it isn't present or false then the code will write to flash, 0x29.

OzFalcon, could you see if it works for you?  Thanks

**Comment by OzFalcon** [comment]
Katie,
I'll give it a whirl to see if it works.

This raises another question or two.
You originally had a control byte of x30, How did you come about this number?
(It would be nice if Andy sent you a description of each bit in the control byte)

And the Pre 2014 ipac4 and MiniIpac also have this x30 byte code - Is this correct?
One would imagine that these devices could also have the Ram_Only bit set too.

**Comment by katie-snow** [comment]
I have access to a minIPAC and I captured the output and found the 0x30.  That is where that came from.

I would guess that the minIPAC and the IPAC4 have the ram option, I am planning on looking into the flash option soon.

**Comment by katie-snow** [comment]
I contacted Andy and the other boards don't have a write to RAM option.  I will make some changes to the pull request #14 and then will be merging it into the master branch.

**Comment by OzFalcon** [comment]
Hi Katie,
Which other boards?

YEAR ID Model
2011: D209:0301 IPac VE
2012: D209:0310 ?? ???
2013: D208:0310 IPac VE
2015: D209:0420 IPac Full

If only the 2011 IPac's had Write to ram option, Then only implement it IF your going to include these older boards in your list of supported devices. ie. https://github.com/katie-snow/Ultimarc-linux/issues/3

**Comment by OzFalcon** [comment]
Unfortunately my 2013-2014 IPac is a value edition. So testing is limited.

What actually happened when you set the write to ram bit while programming your 2013-2014 MiniPac? Did it still write to flash?

**Comment by katie-snow** [comment]
I tried the 2014 IPAC4 and 2014 MinIPAC boards and each one wrote to the flash.

**Comment by OzFalcon** [comment]
With my 2014 IPac Value Edition (No Flash Ram)
I tried writing with the "Reset To Defaults" bit set with a test config expecting it to reset the config to defaults (ie ignore the test config). 
It however programmed the test config, Leading me to think that perhaps both "Write to Ram" and "Reset to Defaults" bits are not active or ignored with 2013-2014 IPac's.

**Comment by OzFalcon** [comment]
I have changed the title of this issue to 2011 IPac cards, And will close it pending your decision on issue #3

**Comment by OzFalcon** [comment]
The write to ram branch should be redundant now.
