### ISSUE TITLE
Has anyone used this with RHEL 7.5 or CentOS 7.5 equiv Linux kernel 3.10.0-862?

### ISSUE THREAD

**Issue by epicgamefan** [katie-snow/Ultimarc-linux#60]
I'm curious because my attempts at interfacing to IPAC devices in this configuration is causing my CPU to  hang up, then I have to hold the power button down to turn off. 
kernel: BUG: soft lockup - CPU#3 stuck for 23s

P.S. have it working in RHEL6 and CentOS6.

**Comment by katie-snow** [comment]
I don't know if you have but this may be answered better on the retropie forums or some other gaming forums.  I haven't tested with this kernel.

**Comment by epicgamefan** [comment]
Its is a bug within the OS/kernel, I've worked with redhat engineers and a
solution has been confirmed and I believe they plan to push the kernel
patch in future RHEL updates.
