### ISSUE TITLE
Support for 2 ServoStiks

### ISSUE THREAD

**Issue by MizterB** [katie-snow/Ultimarc-linux#61]
The ServoStick control board has outputs for 2 servos.  The current umtool implementation appears to only control one output - would it be possible to add logic to independently control the other?

**Comment by katie-snow** [comment]
I shouldn't be to hard to get this implemented.  I am a bit busy right now, so it won't be soon.

**Comment by katie-snow** [comment]
I have looked into this enhancement and the board configures the outputs to be the same.  There is nothing to add to the code.

Closing this issue
