### ISSUE TITLE
Ultistik restrictor value

### ISSUE THREAD

**Issue by maziac** [katie-snow/Ultimarc-linux#67]
I would like to use maps with the ultistik 360.
It is working with the umtool and I can program the stik.
However, I am wondering what the 'restrictor' parameter is used for.

Especially for my configuration: a Ultistik with a servo restrictor plate.
I guess for 4-way and 8-way I should set it to true, but what about 
analog.json. The plate will be still there most probably I set it to 8-way, but what should I  set the restrictor parameter to ?

What actually does the restrictor parameter?

(And because I'm lazy: Are there somewhere more ultistik json files available)

**Comment by katie-snow** [comment]
The Ultistik 360 code has not been working reliably.  And I haven't been able to pin down why, if its old boards pre2015 or OS problem.  If you want to try but make sure you read #50 and are okay if that outcome happens.

The restrictor is for the hardware plate if it is in place or not.  Restricting the second action, for the controller.  Example might be short left before the restrictor is walking, the second long left past the restrictor would be run.  

The umtool will configure the restrictor independent of the analog value.  The restrictor value is true or false, JSON Boolean.

The json files that are in the code base are all I have for configuration files.
