### ISSUE TITLE
Pre 2015 ipac devices only support 28 shifted keys

### ISSUE THREAD

**Issue by OzFalcon** [katie-snow/Ultimarc-linux#7]
Pre 2015 ipac devices only support 28 shifted keys.
The debug output shows umtool writing 32 shifted keys to Pre 2015 devices.
I have also tested a 2015 device - And that does use 32 shifted keys.

See the attached images,
 One shows the umtool output with byte "30" out of place.
 The other shows a test write with the WinIPAC utility.
 The third shows the WinIPAC util not supporting 1A-2B.

I'm not sure what byte "30" does, But the dump sent to me by Andy shows the value "29".
Also, I'd imagine this miss alignment would disrupt any (future) macros being programed.
![208 310 data dump umtool](https://cloud.githubusercontent.com/assets/13824723/9296925/3d3c1692-44da-11e5-9d33-b9a1c31b0abb.png)
![208 310 data dump 1](https://cloud.githubusercontent.com/assets/13824723/9296927/45e1b0a4-44da-11e5-9bae-83615773ba65.png)
![1a-2b do not support shifted values](https://cloud.githubusercontent.com/assets/13824723/9296928/48d5de52-44da-11e5-8b23-eb696d03c832.png)

IPAC Device List
----------------
YEAR	ID	Model	Program
2011: D209:0301	VE	IPacUtil V0.7
2012: D209:0310	??	???
2013: D208:0310 VE	UMTool 
2015: d209:0420 Full	UMTool

**Comment by katie-snow** [comment]
I will look into correcting this.

**Comment by katie-snow** [comment]
The why I had this programmed I was expecting the pre 2015 IPAC2 and MinIPAC to behave the same.  I have the MinIPAC to test with.  The action path is to separate those two boards in the code and make the adjustment for the pre 2015 IPAC2 board.

**Comment by katie-snow** [comment]
I have merged this fix into the master stream.

**Comment by OzFalcon** [comment]
Great, I will check it out as soon as I can and post my results.

**Comment by OzFalcon** [comment]
Katie, I tried programming the following devices and also running without any device connected.
2013: D208:0310
[code]
$ ./umtest.sh ipac2_2014_Default.json 
[INFO] (ultimarc.c:44) Loading ipac2_2014_Default.json...
[ERROR] (ipac.c:116: errno: None) Incorrect number of pin objects.  Needs to be 28 entries.
[INFO] (ultimarc.c:152) Update failed!
[/code]

2015: d209:0420
$ ./umtest.sh ipac2_2015_Default.json 
[INFO] (ultimarc.c:44) Loading ipac2_2015_Default.json...
[ERROR] (ipac.c:116: errno: None) Incorrect number of pin objects.  Needs to be 28 entries.
[INFO] (ultimarc.c:152) Update failed!

No device:
[code]
$ ./umtest.sh ipac2_2014_Default.json 
[INFO] (ultimarc.c:44) Loading ipac2_2014_Default.json...
[ERROR] (ipac.c:116: errno: None) Incorrect number of pin objects.  Needs to be 28 entries.
[INFO] (ultimarc.c:152) Update failed!
[/code]

**Comment by OzFalcon** [comment]
I also tried modifying the .json file for the 28 pin device by removing the shift entries for A1,A2,B1,B2.
Eg:
    "1a": {
      "key": "p"
    },
    "1b": {
      "key": "enter"
    },
    "2a": {
      "key": "tab"
    },
    "2b": {
      "key": "esc"
    }

2013: D208:0310
$ ./umtest.sh ipac2_2014_Default_28pin.json 
[INFO] (ultimarc.c:44) Loading ipac2_2014_Default_28pin.json...
[ERROR] (ipac.c:108: errno: None) pin '1a' has to many children entities.
[ERROR] (ipac.c:108: errno: None) pin '1b' has to many children entities.
[ERROR] (ipac.c:108: errno: None) pin '2a' has to many children entities.
[ERROR] (ipac.c:108: errno: None) pin '2b' has to many children entities.
[ERROR] (ipac.c:116: errno: None) Incorrect number of pin objects.  Needs to be 28 entries.
[INFO] (ultimarc.c:152) Update failed!

**Comment by katie-snow** [comment]
All the errors are JSON file related.  Did you grab the updated ipac2 file?  Could you attach the complete file?

**Comment by OzFalcon** [comment]
On 04/11/15 13:30, Katie wrote:
>
> All the errors are JSON file related. Did you grab the updated ipac2 
> file? Could you attach the complete file?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/katie-snow/Ultimarc-linux/issues/7#issuecomment-153551823>.
>
Oh, Ok I'll use the updated JSON files - Sorry.
Will give it another try with correct configs in a few hours.

**Comment by OzFalcon** [comment]
I have tried the updated ipac2.json file.

It seems the updated ipac2.json file only supports 28 pins. This is not correct.
2013-2014: D208:0310 (Pre 2015 device)
This device has 32 normal pins, 28 shifted pins & 16 macro keys.
You appear to have it programming 28 pins. ie. 1A,2A,1B,2B are missing.
Program:
32 normal pins
28 shifted pins
4 macros of 4 keys each (ie. 16)
(I haven't checked the debug, But the shifted keys are probably out of alignment because the 4 normal pins are not being programed)

The ipac2_2015.json now fails to program the 2015 d209:0420 device.
$ ./umtest.sh ipac2_2015.json 
[INFO] (ultimarc.c:44) Loading ipac2_2015.json...
[ERROR] (ipac.c:116: errno: None) Incorrect number of pin objects.  Needs to be 28 entries.
[INFO] (ultimarc.c:152) Update failed!

**Comment by OzFalcon** [comment]
It would be a good idea to only use one config file and have the tool drop the bytes when programming.
ie. Remove the version number in the json file and have the tool determine if 28 or 32 shifted keys are programmed based on the device ID of the ipac.

The reason this would be helpful is so a (faulty) 2014 ipac can be replaced with a newer (2015) ipac without need for changing config files. Or visa versa.

**Comment by katie-snow** [comment]
I did remove the non-shift 1A,2A,1B,2B, but the way the code is setup the shift keys will be in the right place still.  I will replace the non-shift keys and have the code ignore the shift value.

As for the configurations they are based on version number.  Version 1 is pre-2015 boards, version 2 is 2015 boards.  If you change the version to 2 then the validation code will expect 32 entries.  With adding back in the 4 keys I dropped then versions won't matter as much again for the ipac2.

**Comment by katie-snow** [comment]
I have made another merge of code fixes.  These changes do have the code ignoring the shift keys for 1a, 1b, 2a, 2b key in the configuration file when the configuration is determined to be for pre 2015 IPAC2 boards (version 1).

**Comment by OzFalcon** [comment]
Hi Katie,
I have run the new code fixes and everything seems to be working ok.
(I can attach log files if you want to have a look - But I need write permission to this repository)

Your ipac2.json files seem to still be in a testing state so I have re-written them as correct "Default" configurations as per http://www.ultimarc.com/ipac2.html

I have forked and added the new config files and removed the old test ones.
But have no idea how to merge this fork back to your master (Or do you have to do that?)
