### ISSUE TITLE
UltiStik vs UltraStik

### ISSUE THREAD

**Issue by keilmillerjr** [katie-snow/Ultimarc-linux#71]
I am working on making an AttractMode plugin to automatically switch ServoStik or UltraStik. I reached out to Andy at Ultimarc with a few questions. He mentioned that there is no product called UltiStik. Is this a typo through out Ultimarc-linux? I was under the impression it the product name was changed with revision 2, but guess I was wrong.

**Comment by katie-snow** [comment]
The typo is all me.  It would be worth correcting.

**Comment by keilmillerjr** [comment]
Submitted a pull request.

https://github.com/katie-snow/Ultimarc-linux/pull/73

**Comment by keilmillerjr** [comment]
Any chance to review @katie-snow ?

**Comment by keilmillerjr** [comment]
@katie-snow ?

**Comment by katie-snow** [comment]
Please be patient I will get to the review.  I have been away from my computer for a couple of weeks.

**Comment by keilmillerjr** [comment]
PR accepted and closed. Thank you.
