### ISSUE TITLE
Mini-Pac - Default mouse values wrong in minipac_2015_default.json

### ISSUE THREAD

**Issue by Wavfact** [katie-snow/Ultimarc-linux#77]
I ran the command "./umtool minipac_2015_default.json" and it wiped out mouse buttons left/right..  I had to connect to a windows machine to return to defaults

**Comment by Wavfact** [comment]
It still works in retropie but not recognized by my PC in WinIPac any longer.. I do have the latest version installed..  The mouse left/right buttons no longer work either but trackball still does

**Comment by katie-snow** [comment]
If you want to try again, can you take out the config entry and see if that lets the board configure correctly?  That is the latest change to the configuration file.  Also can you give me the output you get?

**Comment by katie-snow** [comment]
I was able to configure using umtool with the default configuration file with the debounce setting when I switched modes to keyboard. Switching the modes changes the product id.  Keyboard mode is 1 per Ultimarc website.  This is the mode umtool needs minipac to be in to configure the tool.

In addition to the output from umtool please send the output from lsusb?

**Comment by Wavfact** [comment]
I found that my usb cable wasn't plugged in all the way..  but it did wipe out the mouse buttons..  I used WiniPac2 to get them back.

**Comment by katie-snow** [comment]
I will look into making sure the mouse values are correct for the default functionality.
