### ISSUE TITLE
ipac4 from 2011 not working

### ISSUE THREAD

**Issue by aderumier** [katie-snow/Ultimarc-linux#78]
Hi,

I'm trying to program an ipac4 from 2011, but it's not working

```
./umtool --config ipac4_2014_default.json
Loading --config...
[ERROR] (ultimarc.c:70) JSON format invalid
Loading ipac4_2014_default.json...
[INFO] (ultimarc.c:53) Configuration is IPAC4. [Validated]
[INFO] (ipac.c:361) Updating IPAC4 board...
[ERROR] (common.c:90) Unable to claim interface.
[INFO] (ultimarc.c:142) Board update failed.
```

lsub
Bus 001 Device 002: ID d209:0301 Ultimarc I-PAC Arcade Control Interface

I don't see this 0301 in code, and d209 vendorid is defined as 2015 ?

I have tried to add new udev rules, but it's not enough.

I'm able to program it with this old tool
http://www.zumbrovalley.net/ipacutil/dnld/ipacutil_0_7.tar.gz

**Comment by OzFalcon** [comment]
2011 boards are not supported by umtool, They use a different programming method.
[See the readme.md](https://github.com/katie-snow/Ultimarc-linux/blob/master/README.md)
> This library and command line utility support 2012 through 2015 boards. If you need support for older Ultimarc boards, please look at the following utility developed by Travis, Ipacutil or use the Windows WinIpac v1 from Ultimarc

The correct utility is Ipacutil by Travis as you have already found.

**Comment by aderumier** [comment]
ok thanks !
