### ISSUE TITLE
Support for programming Macros to IPAC devices

### ISSUE THREAD

**Issue by OzFalcon** [katie-snow/Ultimarc-linux#8]
Support for programming Macros to IPAC devices.

**Comment by OzFalcon** [comment]
Hi Katie,
I have a suite of common ipac configurations that I'd like to finalize.
Rather than re-working the json files when Macros are supported, Is it possible to pad the config files with macro assignments now, In preparation to when Macros are actually supported my UMTool.

The 2014 cards support 4 macros with 4 bytes each.
The 2015 cards are different and will have to be looked at.

**Comment by katie-snow** [comment]
Yes.  The configuration files can be updated and have the validation put in place now, but not have any of the back end implemented.

**Comment by katie-snow** [comment]
I have added functionality for the support of the macro functionality.  So far the pre-2015 MinIPAC has been validated.  I have also added the functionality to the pre-2015 IPAC2 board, but this is not tested beyond validating the data will be written out.  Currently this is on the macto-support branch (bad spelling job, I know ).

**Comment by OzFalcon** [comment]
Hi Katie,
I have given the new macro build a run, And it appears to be working correctly.
Tests were conducted with the pre-2015 ipac that supports 4x4 macros.
No tests done on the post-2015 ipac yet.

It may not be obvious how to set macros, So I will make a pull request that includes a ipac2_2014_TestMacro.json file.

**Comment by OzFalcon** [comment]
You mentioned the pre-2015 minipac has been validated, Does this mean the post-2015 minipac's are different?

Do ALL the boards need pre/post-2015 json configuration files?
eg.
jpac_2014_default.json
jpac_2015_default.json
ipac4_2014_default.json
ipac4_2015_default.json
minipac_2014_default.json
minipac_2015_default.json

**Comment by katie-snow** [comment]
The format and use of macros in the configuration file will be the same for the 2015 boards as the pre2015 boards.  Validation will be different since there can be more than 4 macro's defined.

**Comment by katie-snow** [comment]
Merged the macro support into the master branch.  The support is for the pre2015 and 2015 IPAC boards, with one exception.  The Ultimate I/O, this board still needs to be merged into the new code for populating IPAC boards, which is where the macro support was added.

**Comment by OzFalcon** [comment]
Great, I'll test the master branch with both Pre & Post 2015 ipac2 cards for a double check.
I'll look at cleaning up some of the default json file names as well.

**Comment by OzFalcon** [comment]
Both Pre & Post 2015 ipac2 boards have been tested and working fine.
Macros work on both boards and everything looks to be ok.

The 2014 board macros can be a bit of a challenge in their programming & usefulness.
(Keys can not be repeated but macros can be chained, And some gray areas inbetween)
As opposed to 2015 board macros which can repeat keys but can not chain macros.
