### ISSUE TITLE
Expansion interface enabled causes shifted keys to repeat

### ISSUE THREAD

**Issue by OzFalcon** [katie-snow/Ultimarc-linux#83]
Test Log
-=-=-=-=
Keytest utility "xev".
Warning: umtool enables the "Expansion interface" by default.
Summary: There appears to be a problem with the "Expansion interface".

Tested with firmware v1.21 (Single Mode)
  The following ocures WITH THE EXPANSION INTERFACE ENABLED.

	Bug (default.json): Shifted P1B1 repeats until another valid key is pressed.
	 Appears to be the same as firmware v1.49 bug.

	Bug (general): ipac2 randomly resets when keys are pressed.

Tested with firmware v1.49 (Single Mode)
  The following ocures WITH THE EXPANSION INTERFACE ENABLED.

	Bug (default.json): Shifted P1B1 repeats until another valid key is pressed.
	 When shifter is pressed (1start) and P1B1 is pressed
	 then shifted P1B1 (5) repeats until another valid key is pressed.
	 [Shifter may be released now while repeating]
		if P1B1 is pressed again then an incorrect transition appears
		and while pressed returns keycode but different state (Resulting in "")
 
	Bug (ReproBug.json): Reproduction of Bug...
	Note: It doesn't matter which button the shifter is assigned
	      to or what it's primary or shifted keys are defined as.
	 When shifter is pressed and ANY button with a primary defined as:
		ctrl l
		ctrl r
		shift l
		shift r
		alt l
		alt r
		win l
		win menu
	then the shifted button value repeats until another valid key is pressed.
	There could be more but that's all I have checked with ReproBug_v149.json
[ipac2_2015_ReproBug_fw149.json.txt](https://github.com/katie-snow/Ultimarc-linux/files/7573983/ipac2_2015_ReproBug_fw149.json.txt)

**Comment by OzFalcon** [comment]
I have it working but the configuration byte structure seems to be wrong.....
@katie-snow Where did you get the configuration byte structure from?
I had to manually test bits to get it working correctly. So an official layout would be handy.

Enumeration is bit 1 being the lsb on the right.
This is what I found (Copy code):
ipac.c
```
void update2015IPAC2Board (json_object *jobj, unsigned char* barray)
{
  json_object *shiftKey = NULL;
  json_object *pins = NULL;
  json_object *macros = NULL;

  /* Header data */
  char header[4] = {0x50, 0xdd, 0x0f, 0x00};
/*
  old config byte
  0x0c = 00001100 = debounce none
  0x10 = 00010000 = debounce Short
  0x14 = 00010100 = debounce Standard
  0x18 = 00011000 = debounce Long
              ^
              This is the "Expansion Enable bit"  (bit 3)
*/
  memcpy (barray, &header, sizeof(header));
  populateConfigurationValue(barray);
//  Force bits 4,5,6
//  barray[3] = 0x38; // = 00111000 = Long
//  barray[3] = 0x18; // = 00011000 = Long 
//  barray[3] = 0x08; // = 00001000 = None
//  barray[3] = 0x10; // = 00010000 = Short
//  barray[3] = 0x30; // = 00110000 = Short
//  barray[3] = 0x00; // = 00000000 = Standard
//  barray[3] = 0xc3; // = 11000011 = Standard
//  Force Bit 3 off
//  barray[3] &= ~(1UL << 2);
//  log_info("    Config Value: 0x%02x", barray[3]);

  /* Setup data to send to board */
```
It DOES NOT APPEAR that bit 6 is required.
ie. Debounce can be set only using bits 4 & 5

**Comment by OzFalcon** [comment]
To implement this the order of bits needed to be re-arranged.
Because there DOES NOT appear to be a debounce_enable bit,
 the bits are re-labeled to help clarify operation and bit identity.
Also because I don't have an official byte layout, I'm not sure the position of the two UIO bits.

ipacseries.h
```
/* Order is important */
union ipacconfig
{
  struct
  {
/*
      // Katies original
      int empty_2 : 1;
      int empty_1 : 1;
      int debounce_pos_5 : 1;
      int debounce_pos_4 : 1;
      int debounce_enabled : 1;
      int paclink : 1;
      int accelerometer_uio : 1;
      int high_current_uio : 1;
*/
      int pending_bit1 : 1;
      int pending_bit2 : 1;
      int paclink_bit3 : 1;
      int debounce_bit4 : 1;
      int debounce_bit5 : 1;
      int debounce_bit6 : 1; //Not used?
      int pending_bit7 : 1;
      int pending_bit8 : 1;
  } parts;
  int config;
};
```

ipacseries.c
```
bool validateConfigDebounce (json_object* config, bool oldValid)
{
  bool valid = oldValid;
  int  lvalue = -1;

  json_object* debounce = NULL;
  const char* debounceStr;

  if (json_object_object_get_ex(config, "debounce", &debounce))
  {
    /*
     * Debounce values; None, Standard, Long, Short
     */
    if (json_object_is_type(debounce, json_type_string))
    {
      debounceStr = json_object_get_string(debounce);
      if (!strcasecmp(debounceStr, "none"))
      {
        piconfig.parts.debounce_bit4 = 1;
        piconfig.parts.debounce_bit5 = 0;
        piconfig.parts.debounce_bit6 = 0; ////Not used?
        lvalue = 0;
      }
      if (!strcasecmp(debounceStr, "standard"))
      {
        piconfig.parts.debounce_bit4 = 0;
        piconfig.parts.debounce_bit5 = 0;
        piconfig.parts.debounce_bit6 = 0; ////Not used?
        lvalue = 0;
      }
      if (!strcasecmp(debounceStr, "long"))
      {
        piconfig.parts.debounce_bit4 = 1;
        piconfig.parts.debounce_bit5 = 1;
        piconfig.parts.debounce_bit6 = 0; ////Not used?
        lvalue = 0;
      }
      if (!strcasecmp(debounceStr, "short"))
      {
        piconfig.parts.debounce_bit4 = 0;
        piconfig.parts.debounce_bit5 = 1;
        piconfig.parts.debounce_bit6 = 0; ////Not used?
        lvalue = 0;
      }
```

**Comment by OzFalcon** [comment]
These changes have been tested and are working with 2015 ipac2 firmware 1.49.
Confirmation was made by writing the ipac2 with umtool then checking it with WinIPAC v1.08.12.

I'll wait on your response regarding the ipac2 configuration byte structure/layout before pushing these changes.

**Comment by katie-snow** [comment]
Andy sent me the configuration document, but it didn't have the debounce and expansion interface stated in the configuration bit.  I generated the information on my own and I agree that I miss read the bits in the configuration.   bit 6 is the expansion bit not another debounce.  It most likely has been this way since it was introduced.

**Comment by OzFalcon** [comment]
@katie-snow 
Sounds like an easy fix. So just to confirm - The UIO's - are the most significant bits (7 & 8) of the byte?
See example below.

ipacseries.h
```
/* Order is important */
union ipacconfig
{
  struct
  {
/*
      // Katies original
      int empty_2 : 1;
      int empty_1 : 1;
      int debounce_pos_5 : 1;
      int debounce_pos_4 : 1;
      int debounce_enabled : 1;
      int paclink : 1;
      int accelerometer_uio : 1;
      int high_current_uio : 1;
*/
      // New struct
      int empty : 1;			//Bit1
      int empty : 1;			//Bit2
      int paclink : 1;			//Bit3
      int debounce_1 : 1;		//Bit4
      int debounce_2 : 1;		//Bit5
      int empty : 1;			//Bit6
      int accelerometer_uio : 1;	//Bit7
      int high_current_uio : 1;	//Bit8
  } parts;
  int config;
};
```

**Comment by katie-snow** [comment]
struct
  {
    int empty_2 : 1;                         // bit 0
    int empty_1 : 1;                         // bit 1
    int empty_0 : 1;                         // bit 2
    int debounce_1: 1;                    // bit 3
    int debounce_2 : 1;                   // bit 4
    int paclink : 1;                            // bit 5
    int accelerometer_uio : 1;         // bit 6
    int high_current_uio : 1;            // bit 7
  } parts;
  int config;


In the document Andy sent it did have the paclink next to accelerometer.  So my comments in the code are incorrect but the name location for paclink is correct.

**Comment by OzFalcon** [comment]
@katie-snow
The paclink is bit 2, If we force bit 2 and flash the ipac then the "Expansion Interface" checks as enabled under WinIPAC2.
Example:
//  Force bit 2
//  barray[3] = 0x04; // = 000000100 = paclink enabled

And if paclink is next to accelerometer, Then the only place accelerometer & high_current can be is bits 0 & 1.
Like this:
ipacseries.h
```
/* Order is important */
union ipacconfig
{
  struct
  {
/*
      // Katies original
      int empty_2 : 1;
      int empty_1 : 1;
      int debounce_pos_5 : 1;
      int debounce_pos_4 : 1;
      int debounce_enabled : 1;
      int paclink : 1;
      int accelerometer_uio : 1;
      int high_current_uio : 1;
*/
      // New struct
      int high_current_uio : 1;		//Bit0
      int accelerometer_uio : 1;	//Bit1
      int paclink : 1;			//Bit2
      int debounce_1 : 1;		//Bit3
      int debounce_2 : 1;		//Bit4
      int empty : 1;			//Bit5
      int empty : 1;			//Bit7
      int empty : 1;			//Bit8
  } parts;
  int config;
};
```

**Comment by OzFalcon** [comment]
Ultimarc website has these two documents referencing the paclink/expansion interface.
https://www.ultimarc.com/console-adapters/console-adapters/paclink-adaptor-en/
https://www.ultimarc.com/control-interfaces/i-pacs/i-pac2/    (Under the installation Tab)

**Comment by katie-snow** [comment]
It looks like I got my endian's mixed up when I was creating this structure.  All I can figure is I miss read the control_transfer documentation when it talks about endian.  Anyway, yes the structure should look like the last entry, 

      int high_current_uio : 1;    //Bit0
      int accelerometer_uio : 1;	//Bit1
      int paclink : 1;			//Bit2
      int debounce_1 : 1;		//Bit3
      int debounce_2 : 1;		//Bit4
      int empty : 1;			//Bit5
      int empty : 1;			//Bit6
      int empty : 1;			//Bit7

**Comment by OzFalcon** [comment]
I'll push that in the next day or so.

**Comment by OzFalcon** [comment]
@katie-snow 
That should be ok now plus a few cleanups.
My branch/commits got a bit mixed up on the README changes, no conflicts though.
