### ISSUE TITLE
 Aimtrak setup script: Line 51: print(f'{fileStr} already exists!  Not overwriting!') syntax error

### ISSUE THREAD

**Issue by PieterJanSterk** [katie-snow/Ultimarc-linux#88]
When I run the aimtrak setup script, I get the following error:

```
  File "aimtrak_setup.py", line 51
    print(f'{fileStr} already exists!  Not overwriting!')
                                                       ^
SyntaxError: invalid syntax
```

Is this a Python version error or something stupid on my end? Thanks in advance!

**Comment by OzFalcon** [comment]
The readme mentions Python 3, Have you followed the steps in
https://github.com/katie-snow/Ultimarc-linux/blob/master/scripts/aimtrak_readme

I'm not up to speed on python but this post mentions Python 3.6 introducing f-strings
https://stackoverflow.com/questions/19457227/how-to-print-like-printf-in-python3

Check your Python version is >3.6

**Comment by OzFalcon** [comment]
Seems to run fine on this end.
```
python -V
Python 3.9.2

python aimtrak_setup.py -s
[sudo] password for me: 
Writing /etc/udev/rules.d/65-aimtrak.rules
Writing /etc/X11/xorg.conf.d/60-aimtrak.conf

run "sudo udevadm control --reload-rules && sudo udevadm trigger" or restart machine to apply changes.
```

**Comment by PieterJanSterk** [comment]
Sorry, python version seems to be the error here. It was an older Rasbian image (which contained both Python 2.7 and Python 3.7).

Ran command as `python3 aimtrak_setup.py -s` which solves everything.
