### ISSUE TITLE
Release UMTool V1.2.0

### ISSUE THREAD

**Issue by OzFalcon** [katie-snow/Ultimarc-linux#89]
I think there have been enough fixes to warrant a V1.2.0 release.
I know when I am trying out software I will download the latest "release" package.
And currently the V1.1.0 release is broken due to #82 & #85.

I'm not exactly sure where all the references to release number are, But I'll
post any queries looking at it here for confirmation.

**Comment by OzFalcon** [comment]
I'm not sure about https://github.com/katie-snow/Ultimarc-linux/blob/master/ultimarc.spec
Minor & Major numbers are fine, But why the release number is 14....?
Shouldn't this be release #3 --> updating to release #4
```
%define name ultimarc
%define major 1
%define minor 1
%define release 14
%define version %{major}.%{minor}
```

**Comment by OzFalcon** [comment]
I think that might be it. Only two locations the version number is referenced.
1: https://github.com/katie-snow/Ultimarc-linux/blob/master/configure.ac
2: https://github.com/katie-snow/Ultimarc-linux/blob/master/ultimarc.spec

Also the updated ChangeLog (Pull request pending) would need the <DATE> added for the V1.2.0 release.
https://github.com/katie-snow/Ultimarc-linux/blob/master/ChangeLog

**Comment by katie-snow** [comment]
The release number would be used for nightly builds if that was setup. 
Added date to ChangeLog and created the new release.
